# docker-compose.yml
name: tg-bot

services:
  bot:
    container_name: bot
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      TGKEY: ${TGKEY}
      CHATID: ${CHATID}
      GEMINI_KEY: ${GEMINI_KEY}
      CI_SECRET: ${CI_SECRET}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host_root:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - backend

  nginx:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.nginx
    container_name: nginx
    ports:
      - "8001:80"
      # - "443:443" если нужен HTTPS
    depends_on:
      - bot
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
