# Dockerfile.nginx
FROM nginx:1.29.2-alpine-slim

# Удаляем дефолтные конфиги nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем конфиг
COPY Docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY Docker/nginx/nginx-app.conf /etc/nginx/conf.d/default.conf


# Создаем директорию для логов
RUN mkdir -p /var/log/nginx

EXPOSE 80