name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        id: pytest_step
        continue-on-error: true  # <--- не прерываем workflow при ошибках
        run: |
          pytest -v --disable-warnings

      - name: Send CI Report to Telegram Bot
        if: always()  # <--- гарантируем выполнение даже если тесты упали
        env:
          CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
          SECRET: ${{ secrets.CI_SECRET }}
        run: |
          STATUS="✅ Тесты пройдены"
          if [ "${{ steps.pytest_step.outcome }}" != "success" ]; then
            STATUS="❌ Тесты не пройдены"
          fi
          curl -X POST "$CI_ENDPOINT" \
            -H "Content-Type: application/json" \
            -d '{
              "secret": "'"$SECRET"'",
              "project": "'"${{ github.repository }}"'",
              "status": "'"$STATUS"'",
              "commit": "'"$(git rev-parse --short HEAD)"'",
              "author": "'"${{ github.actor }}"'",
              "branch": "'"${{ github.ref_name }}"'",
              "workflow": "'"${{ github.workflow }}"'",
              "event_name": "'"${{ github.event_name }}"'",
              "message": "'"${{ github.event.head_commit.message || '' }}"'",
              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "repo_url": "https://github.com/${{ github.repository }}"
            }'
